version: "3.9"
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bank
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d bank" ]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/bank?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
