#name: cd
#
#on:
#  workflow_run:
#    workflows: [ "ci-build" ]
#    types:
#      - completed
#
#jobs:
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    permissions:
#      id-token: write
#      contents: read
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v3
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          role-to-assume: arn:aws:iam::691474667905:role/GithubActions
#          aws-region: us-east-1
#      - uses: azure/setup-kubectl@v3
#        id: install
#      - name: Update kube config
#        run: aws eks update-kubeconfig --name golang-bank --region us-east-1
#      - name: Deploy to EKS
#        run: |
#          kubectl apply -f kubernetes/aws-auth.yml
#          kubectl apply -f kubernetes/deployment.yml
#          kubectl apply -f kubernetes/service.yml
#          kubectl apply -f kubernetes/issuer.yml
#          kubectl apply -f kubernetes/ingress.yml
